class AlreadyExistsError(Exception):
    pass


class ExternalError(Exception):
    pass
